image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build artifact
        script:
               - apt-get update && apt-get install -y python3-pip 
               - pip3 install -U awscli 
               - s3 --region "ap-south-1" rm s3://myreact-bucket
               - s3 --region "ap-south-1" sync . s3://myreact-bucket