image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build artifact
        script:
           - s3 --region "ap-south-1" rm s3://myreact-bucket
            - s3 --region "ap-south-1" sync . s3://myreact-bucket