image: node:16

# Workflow Configuration

pipelines:
  default:
      - step:
          script:
            - apt-get update && apt-get install -y python3-pip 
            - pip3 install -U awscli 
            - aws --version
            - aws s3 mb s3://myreact-s3-d6