image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build artifact
        script:
               - apt-get update && apt-get install -y python3-pip 
               - pip3 install -U awscli 
               - /bin/bash deploy.sh